# Site settings
name: Atomix
email: sincerehwh@126.com
author: louis han
url: http://www.sincerehwh.top

github: https://github.com/sincerehwh/
baseurl: ""
description: Seeking truth from facts.
meta_description: 韩文鹤;个人博客;生命不息,折腾不止.
motto: 自强-自律.
banner: 学而不思则罔，思而不学则殆。

permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: sincerehwh

# Build settings
markdown: kramdown

baidu_analysis: 624f97ab37fd73fbedc7929427ca95ea

